#!/bin/bash

default="\033[39m"
black="\033[30m"
red="\033[31m"
green="\033[32m"
yellow="\033[33m"
blue="\033[34m"
magenta="\033[35m"
cyan="\033[36m"
gray="\033[90m"
white="\033[97m"
reset="\033[0m"
bold="\033[1m"
underline="\033[4m"

cmd="${@:1}"
echo -e "$ ${cyan}${cmd}${reset}"

declare -a folders=("fold1 fold2 ...")

for folder in "${folders[@]}"
do
    echo -e
    echo -e "${yellow}[${folder}]${reset}"
    cd $folder
    eval $cmd
    cd ..
done
